name: 07 - Download Website from S3

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  download-from-s3:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::889088857850:role/github-role-tier2
          aws-region: sa-east-1

      - name: Download website.zip on EC2 using SSM
        run: |

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-07653cf973456d7cf" \
            --document-name "AWS-RunShellScript" \
            --comment "Download website.zip from S3" \
            --parameters 'commands=[
              "sudo mkdir -p /tmp/website",
              "cd /tmp/website",
              "aws s3 cp s3://terraform-in-one-shot2003/website.zip .",
              "ls -lh /tmp/website"
            ]' \
            --region sa-east-1 \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "i-07653cf973456d7cf" \
            --region sa-east-1

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "i-07653cf973456d7cf" \
            --region sa-east-1